[2025-10-15T00:15:23.790+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-15T00:15:24.769+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_etl.extract_task scheduled__2025-10-14T00:00:00+00:00 [queued]>
[2025-10-15T00:15:24.994+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_etl.extract_task scheduled__2025-10-14T00:00:00+00:00 [queued]>
[2025-10-15T00:15:25.004+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-10-15T00:15:25.290+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_task> on 2025-10-14 00:00:00+00:00
[2025-10-15T00:15:25.371+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3577) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-15T00:15:25.373+0000] {standard_task_runner.py:64} INFO - Started process 3579 to run task
[2025-10-15T00:15:25.376+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_market_etl', 'extract_task', 'scheduled__2025-10-14T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/stock_etl_dag.py', '--cfg-path', '/tmp/tmpibpjgtwk']
[2025-10-15T00:15:25.380+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask extract_task
[2025-10-15T00:15:25.523+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_market_etl.extract_task scheduled__2025-10-14T00:00:00+00:00 [running]> on host 9d4269c8615b
[2025-10-15T00:15:34.249+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_market_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-14T00:00:00+00:00'
[2025-10-15T00:15:34.250+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-15T00:15:34.280+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-15T00:15:34.281+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_etl_dag.py", line 20, in extract_stock_data
    raise ValueError("API_KEY environment variable is not set")
ValueError: API_KEY environment variable is not set
[2025-10-15T00:15:34.303+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_market_etl, task_id=extract_task, run_id=scheduled__2025-10-14T00:00:00+00:00, execution_date=20251014T000000, start_date=20251015T001524, end_date=20251015T001534
[2025-10-15T00:15:34.345+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task extract_task (API_KEY environment variable is not set; 3579)
[2025-10-15T00:15:34.367+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-15T00:15:34.397+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-15T00:15:34.488+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
